- name: Package Application
  uses: JackMcKew/pyinstaller-action-windows@main
  with:
    path: maliang_ui
    python_version: "3.12" # 关键：指定 Python 3.12
    pypi_url: https://pypi.org/simple/
    pypi_index_url: https://pypi.org/simple/
